language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "kiwiproject"
    token:
      secure: "P1dOhvnsDyeJ2yQudDlaS2uDdmxOrbq4DJdZVD7aXRbjw8QOE1uj7rYeRvBlckTx/ffB7YuNr8yxZTHFHqSoWzirJwQNnuHcjbdQP3b4qFAPOd9Gt8EZWKtiPhh+LC3cxwhxNDVK4m4nU618JJq8BbdBlSmyUja6HEFe03Lj1dbbMRxgzRUKexGpoyylSewdE4m75g3qqpmCHQsHwQJnXmbYLgQrtlYjeCOhZbMMRtiearp8nl1E0b3gyccMsqxU/DfHnkBiFZQH1bve5zicDpeWKq3LpGYteOHI6RB7GjsvaYu4M8HfA4ku8flunz9p5uojYFDldkuhJGEftNPizpP52CanOBA/JvrqPXOYkjejxxfwt94yI8CtZCrRT3xDgZBw1F8CW6uNq9EjYt6+/PC5Lhp5E2iil9Lj6GOgH/WPqZ5minT+DAKISKyUuAdRku0L0574oXAW82MsR/MfptRvNCSxgiFuHLnYarb+7gZ2EJWk8WHCT0FlITQsUlzpj6mX3ItDqCUkLwjv7vm5dEGRNyW5B4nGuNYpba3c8oHoCznIzmRHJlPp9rfHQaXk0Jdu5bhPpUPSbBSdzrqIcb5pBnGvmyRzwkWyAs2rDYY4dU7qu8b2eGEWUp+UTqGqWrATlDGh1SitJmK2M2PD4q3mqyCG+UgqWVv2S0texQk="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=kiwiproject_kiwi-test
